import Motorcycle from '../models/Motorcycle'
import { MotorcycleCategory } from '../models/Motorcycle'
import Brand from '../models/Brand'
import { connectToMongo } from '.'

const seedMotorcycles = async () => {
  await connectToMongo()
  await Motorcycle.deleteMany({})

  // Récupérer les brands pour avoir leurs vrais _id MongoDB
  const brands = await Brand.find()
  const brandByName = (name: string) => {
    const brand = brands.find((b) => b.name === name)
    if (!brand)
      throw new Error(
        `Brand "${name}" introuvable. Lancez le seed brand d'abord.`,
      )
    return brand._id
  }

  await Motorcycle.insertMany([
    {
      brand: brandByName('Honda'),
      engine_size: 599,
      name: 'CBR600RR',
      horsePower: 121,
      torque: 66,
      weight: 194,
      consumption: 5.9,
      category: MotorcycleCategory.SPORTSBIKE,
      isAvailableA2: false,
      year: 2020,
      price: 12000,
      numberOfComparison: 3,
      withAllField: false,
      is_public: false,
      speedMax: 257,
      soundLink: '/sounds/CBR600RR.mp3',
    },
    {
      brand: brandByName('Kawasaki'),
      engine_size: 636,
      name: 'Ninja ZX-6R',
      horsePower: 130,
      torque: 70.8,
      weight: 196,
      consumption: 6.1,
      category: MotorcycleCategory.SPORTSBIKE,
      isAvailableA2: false,
      year: 2021,
      price: 11500,
      numberOfComparison: 5,
      withAllField: false,
      is_public: false,
      speedMax: 262,
    },
    {
      brand: brandByName('Suzuki'),
      engine_size: 599,
      name: 'GSX-R600',
      horsePower: 125,
      torque: 66.9,
      weight: 187,
      consumption: 5.7,
      category: MotorcycleCategory.SPORTSBIKE,
      isAvailableA2: false,
      year: 2019,
      price: 11000,
      numberOfComparison: 2,
      withAllField: false,
      is_public: false,
      speedMax: 250,
    },
    {
      brand: brandByName('Yamaha'),
      engine_size: 599,
      name: 'YZF-R6',
      horsePower: 118,
      torque: 61.7,
      weight: 190,
      consumption: 5.8,
      category: MotorcycleCategory.SPORTSBIKE,
      isAvailableA2: false,
      year: 2020,
      price: 11800,
      numberOfComparison: 4,
      withAllField: false,
      is_public: false,
      speedMax: 257,
    },
    {
      brand: brandByName('Ducati'),
      engine_size: 955,
      name: 'Panigale V2',
      horsePower: 155,
      torque: 104,
      weight: 200,
      consumption: 6.4,
      category: MotorcycleCategory.SPORTSBIKE,
      isAvailableA2: false,
      year: 2023,
      price: 17990,
      numberOfComparison: 8,
      withAllField: true,
      is_public: true,
      soundLink: 'https://example.com/sounds/panigale-v2.mp3',
      time_0_100: 3.3,
      time_100_200: 6.1,
      time_200_300: 999,
      speedMax: 270,
    },
    {
      brand: brandByName('BMW'),
      engine_size: 999,
      name: 'S1000RR',
      horsePower: 210,
      torque: 113,
      weight: 197,
      consumption: 6.4,
      category: MotorcycleCategory.SPORTSBIKE,
      isAvailableA2: false,
      imageUrl: '/images/motorcycles/S1000RR.png',
      year: 2024,
      price: 21990,
      numberOfComparison: 12,
      withAllField: false,
      is_public: true,
      time_0_100: 3.1,
      speedMax: 303,
    },
    {
      brand: brandByName('Honda'),
      engine_size: 998,
      name: 'CBR1000RR-R Fireblade',
      horsePower: 217,
      torque: 113,
      weight: 201,
      consumption: 6.8,
      category: MotorcycleCategory.SPORTSBIKE,
      isAvailableA2: false,
      year: 2024,
      price: 24599,
      numberOfComparison: 10,
      withAllField: false,
      is_public: true,
      time_0_100: 3.2,
      speedMax: 299,
    },
    {
      brand: brandByName('Yamaha'),
      engine_size: 998,
      name: 'YZF-R1',
      horsePower: 200,
      torque: 112.4,
      weight: 200,
      consumption: 6.5,
      category: MotorcycleCategory.SPORTSBIKE,
      isAvailableA2: false,
      imageUrl: '/images/motorcycles/YZF-R1.png',
      year: 2023,
      price: 19999,
      numberOfComparison: 9,
      withAllField: false,
      is_public: true,
      time_0_100: 3.0,
      speedMax: 299,
    },
    {
      brand: brandByName('Ducati'),
      engine_size: 1099,
      name: 'Streetfighter V4',
      horsePower: 208,
      torque: 123,
      weight: 199,
      consumption: 7.0,
      category: MotorcycleCategory.ROADSTER,
      isAvailableA2: false,
      year: 2024,
      price: 23990,
      numberOfComparison: 6,
      withAllField: false,
      is_public: true,
      speedMax: 290,
    },
    {
      brand: brandByName('Kawasaki'),
      engine_size: 1043,
      name: 'Z H2',
      horsePower: 200,
      torque: 137,
      weight: 239,
      consumption: 6.7,
      category: MotorcycleCategory.ROADSTER,
      isAvailableA2: false,
      year: 2023,
      price: 18500,
      numberOfComparison: 7,
      withAllField: false,
      is_public: true,
      time_0_100: 3.4,
      speedMax: 280,
    },
    {
      brand: brandByName('Honda'),
      engine_size: 599,
      name: 'CBR600RR',
      horsePower: 121,
      torque: 66,
      weight: 194,
      consumption: 5.9,
      category: MotorcycleCategory.SPORTSBIKE,
      isAvailableA2: false,
      year: 2021,
      price: 12000,
      numberOfComparison: 3,
      withAllField: false,
      is_new: false,
      speedMax: 257,
    },
    // Motos A2
    {
      brand: brandByName('Honda'),
      engine_size: 471,
      name: 'CB500F',
      horsePower: 47,
      torque: 43,
      weight: 189,
      consumption: 3.5,
      category: MotorcycleCategory.ROADSTER,
      isAvailableA2: true,
      year: 2024,
      price: 6799,
      numberOfComparison: 0,
      withAllField: false,
      is_new: true,
      speedMax: 191,
    },
    {
      brand: brandByName('Yamaha'),
      engine_size: 689,
      name: 'MT-07',
      horsePower: 73,
      torque: 67,
      weight: 184,
      consumption: 4.0,
      category: MotorcycleCategory.ROADSTER,
      isAvailableA2: true,
      year: 2024,
      price: 7599,
      numberOfComparison: 0,
      withAllField: false,
      is_new: true,
      speedMax: 200,
    },
    {
      brand: brandByName('Kawasaki'),
      engine_size: 649,
      name: 'Z650',
      horsePower: 68,
      torque: 64,
      weight: 187,
      consumption: 4.2,
      category: MotorcycleCategory.ROADSTER,
      isAvailableA2: true,
      year: 2024,
      price: 7399,
      numberOfComparison: 0,
      withAllField: false,
      is_new: true,
      speedMax: 195,
    },
    {
      brand: brandByName('Suzuki'),
      engine_size: 645,
      name: 'SV650',
      horsePower: 73,
      torque: 64,
      weight: 197,
      consumption: 4.1,
      category: MotorcycleCategory.ROADSTER,
      isAvailableA2: true,
      year: 2023,
      price: 7199,
      numberOfComparison: 0,
      withAllField: false,
      is_new: false,
      speedMax: 198,
    },
    // Motos Adventure
    {
      brand: brandByName('Honda'),
      engine_size: 1084,
      name: 'Africa Twin',
      horsePower: 102,
      torque: 105,
      weight: 226,
      consumption: 5.2,
      category: MotorcycleCategory.ADVENTURE,
      isAvailableA2: false,
      year: 2024,
      price: 15999,
      numberOfComparison: 0,
      withAllField: false,
      is_new: true,
      speedMax: 210,
    },
    {
      brand: brandByName('BMW'),
      engine_size: 1254,
      name: 'R 1250 GS',
      horsePower: 136,
      torque: 143,
      weight: 249,
      consumption: 5.6,
      category: MotorcycleCategory.ADVENTURE,
      isAvailableA2: false,
      year: 2024,
      price: 19650,
      numberOfComparison: 0,
      withAllField: false,
      is_new: true,
      speedMax: 220,
    },
    {
      brand: brandByName('Yamaha'),
      engine_size: 1199,
      name: 'Super Ténéré 1200',
      horsePower: 112,
      torque: 117,
      weight: 265,
      consumption: 5.4,
      category: MotorcycleCategory.ADVENTURE,
      isAvailableA2: false,
      year: 2023,
      price: 17499,
      numberOfComparison: 0,
      withAllField: false,
      is_new: false,
      speedMax: 215,
    },
    {
      brand: brandByName('Ducati'),
      engine_size: 1158,
      name: 'Multistrada V4',
      horsePower: 170,
      torque: 125,
      weight: 218,
      consumption: 5.8,
      category: MotorcycleCategory.ADVENTURE,
      isAvailableA2: false,
      year: 2024,
      price: 22990,
      numberOfComparison: 0,
      withAllField: false,
      is_new: true,
      speedMax: 240,
    },
    // Motos A2 supplémentaires
    {
      brand: brandByName('Kawasaki'),
      engine_size: 649,
      name: 'Ninja 650',
      horsePower: 68,
      torque: 64,
      weight: 192,
      consumption: 4.3,
      category: MotorcycleCategory.SPORTSBIKE,
      isAvailableA2: true,
      year: 2024,
      price: 7999,
      numberOfComparison: 0,
      withAllField: false,
      is_new: true,
      speedMax: 206,
    },
    {
      brand: brandByName('Yamaha'),
      engine_size: 689,
      name: 'Ténéré 700',
      horsePower: 73,
      torque: 68,
      weight: 204,
      consumption: 3.9,
      category: MotorcycleCategory.ADVENTURE,
      isAvailableA2: true,
      year: 2024,
      price: 9999,
      numberOfComparison: 0,
      withAllField: false,
      is_new: true,
      speedMax: 187,
    },
    {
      brand: brandByName('Honda'),
      engine_size: 471,
      name: 'CBR500R',
      horsePower: 47,
      torque: 43,
      weight: 194,
      consumption: 3.6,
      category: MotorcycleCategory.SPORTSBIKE,
      isAvailableA2: true,
      year: 2024,
      price: 7199,
      numberOfComparison: 0,
      withAllField: false,
      is_new: true,
      speedMax: 183,
    },
    {
      brand: brandByName('Suzuki'),
      engine_size: 248,
      name: 'V-Strom 250 SX',
      horsePower: 26,
      torque: 22,
      weight: 167,
      consumption: 2.8,
      category: MotorcycleCategory.ADVENTURE,
      isAvailableA2: true,
      year: 2024,
      price: 4799,
      numberOfComparison: 0,
      withAllField: false,
      is_new: true,
      speedMax: 140,
    },
    // Adventure supplémentaires
    {
      brand: brandByName('Kawasaki'),
      engine_size: 1043,
      name: 'Versys 1000 SE',
      horsePower: 120,
      torque: 102,
      weight: 257,
      consumption: 5.8,
      category: MotorcycleCategory.ADVENTURE,
      isAvailableA2: false,
      year: 2024,
      price: 16999,
      numberOfComparison: 0,
      withAllField: false,
      is_new: true,
      speedMax: 230,
    },
    {
      brand: brandByName('BMW'),
      engine_size: 1254,
      name: 'R 1250 GS Adventure',
      horsePower: 136,
      torque: 143,
      weight: 268,
      consumption: 5.9,
      category: MotorcycleCategory.ADVENTURE,
      isAvailableA2: false,
      year: 2024,
      price: 22350,
      numberOfComparison: 0,
      withAllField: false,
      is_new: true,
      speedMax: 215,
    },
  ])

  console.log('Motorcycles seeded')
}

export default seedMotorcycles
